/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'
import { Route as ApiPublicPanelLogsRouteImport } from './routes/api/public/panel-logs'
import { Route as ApiPublicEmployeeRouteImport } from './routes/api/public/employee'
import { Route as ApiPublicDeptCodeRouteImport } from './routes/api/public/dept-code'
import { Route as ApiPublicDepartmentsRouteImport } from './routes/api/public/departments'
import { Route as ApiPublicAttendanceRouteImport } from './routes/api/public/attendance'
import { Route as ApiPublicAddFaceDataRouteImport } from './routes/api/public/add-face-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPanelLogsRoute = ApiPublicPanelLogsRouteImport.update({
  id: '/api/public/panel-logs',
  path: '/api/public/panel-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmployeeRoute = ApiPublicEmployeeRouteImport.update({
  id: '/api/public/employee',
  path: '/api/public/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeptCodeRoute = ApiPublicDeptCodeRouteImport.update({
  id: '/api/public/dept-code',
  path: '/api/public/dept-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDepartmentsRoute = ApiPublicDepartmentsRouteImport.update({
  id: '/api/public/departments',
  path: '/api/public/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttendanceRoute = ApiPublicAttendanceRouteImport.update({
  id: '/api/public/attendance',
  path: '/api/public/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAddFaceDataRoute = ApiPublicAddFaceDataRouteImport.update({
  id: '/api/public/add-face-data',
  path: '/api/public/add-face-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/attendance': typeof ApiPublicAttendanceRoute
  '/api/public/departments': typeof ApiPublicDepartmentsRoute
  '/api/public/dept-code': typeof ApiPublicDeptCodeRoute
  '/api/public/employee': typeof ApiPublicEmployeeRoute
  '/api/public/panel-logs': typeof ApiPublicPanelLogsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/add-face-data': typeof ApiPublicAddFaceDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/attendance': typeof ApiPublicAttendanceRoute
  '/api/public/departments': typeof ApiPublicDepartmentsRoute
  '/api/public/dept-code': typeof ApiPublicDeptCodeRoute
  '/api/public/employee': typeof ApiPublicEmployeeRoute
  '/api/public/panel-logs': typeof ApiPublicPanelLogsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/add-face-data': typeof ApiPublicAddFaceDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/attendance': typeof ApiPublicAttendanceRoute
  '/api/public/departments': typeof ApiPublicDepartmentsRoute
  '/api/public/dept-code': typeof ApiPublicDeptCodeRoute
  '/api/public/employee': typeof ApiPublicEmployeeRoute
  '/api/public/panel-logs': typeof ApiPublicPanelLogsRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
  '/api/public/add-face-data': typeof ApiPublicAddFaceDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/attendance'
    | '/api/public/departments'
    | '/api/public/dept-code'
    | '/api/public/employee'
    | '/api/public/panel-logs'
    | '/api/public/sync'
    | '/api/public/add-face-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/attendance'
    | '/api/public/departments'
    | '/api/public/dept-code'
    | '/api/public/employee'
    | '/api/public/panel-logs'
    | '/api/public/sync'
    | '/api/public/add-face-data'
  id:
    | '__root__'
    | '/'
    | '/api/public/attendance'
    | '/api/public/departments'
    | '/api/public/dept-code'
    | '/api/public/employee'
    | '/api/public/panel-logs'
    | '/api/public/sync'
    | '/api/public/add-face-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAttendanceRoute: typeof ApiPublicAttendanceRoute
  ApiPublicDepartmentsRoute: typeof ApiPublicDepartmentsRoute
  ApiPublicDeptCodeRoute: typeof ApiPublicDeptCodeRoute
  ApiPublicEmployeeRoute: typeof ApiPublicEmployeeRoute
  ApiPublicPanelLogsRoute: typeof ApiPublicPanelLogsRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
  ApiPublicAddFaceDataRoute: typeof ApiPublicAddFaceDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/panel-logs': {
      id: '/api/public/panel-logs'
      path: '/api/public/panel-logs'
      fullPath: '/api/public/panel-logs'
      preLoaderRoute: typeof ApiPublicPanelLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/employee': {
      id: '/api/public/employee'
      path: '/api/public/employee'
      fullPath: '/api/public/employee'
      preLoaderRoute: typeof ApiPublicEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/departments': {
      id: '/api/public/departments'
      path: '/api/public/departments'
      fullPath: '/api/public/departments'
      preLoaderRoute: typeof ApiPublicDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dept-code': {
      id: '/api/public/dept-code'
      path: '/api/public/dept-code'
      fullPath: '/api/public/dept-code'
      preLoaderRoute: typeof ApiPublicDeptCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attendance': {
      id: '/api/public/attendance'
      path: '/api/public/attendance'
      fullPath: '/api/public/attendance'
      preLoaderRoute: typeof ApiPublicAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/add-face-data': {
      id: '/api/public/add-face-data'
      path: '/api/public/add-face-data'
      fullPath: '/api/public/add-face-data'
      preLoaderRoute: typeof ApiPublicAddFaceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAttendanceRoute: ApiPublicAttendanceRoute,
  ApiPublicDepartmentsRoute: ApiPublicDepartmentsRoute,
  ApiPublicDeptCodeRoute: ApiPublicDeptCodeRoute,
  ApiPublicEmployeeRoute: ApiPublicEmployeeRoute,
  ApiPublicPanelLogsRoute: ApiPublicPanelLogsRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
  ApiPublicAddFaceDataRoute: ApiPublicAddFaceDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
